name: MinecraftMarket
main: com.minecraftmarket.Market
version: 1.5
website: http://www.minecraftmarket.com
commands:
    mm:
        description: MinecraftMarket main command
    shop:
        description: Open shop for player
