name: MinecraftMarket
main: com.minecraftmarket.Market
version: 1.4
website: http://www.minecraftmarket.com
commands:
    store:
        description: Open store for player
    mm:
        description: Changes the API KEY in the config.yml
