name: MinecraftMarket
main: com.minecraftmarket.Market
version: 1.4
website: http://www.minecraftmarket.com
commands:
    mmreload:
        description: reload config
    mmcheck:
        description: force check for new purchases
    shop:
        description: Open shop for player
    mmapikey:
        description: Changes the API KEY in the config.yml
